[package]
name = "tergo"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Fromat code written in R"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
tergo-lib = { path = "../lib" }
