[package]
name = "tokenizer"
version = "0.1.0"
edition = "2021"
authors = ["Konrad Pagacz konrad.pagacz@gmail.com"]
description = "R language tokenizer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
