on:
  push:
    branches: [main]
    paths:
      - "antidotum/**"

name: Version bump

permissions: read-all

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/create-github-app-token@v1
        id: minion-token
        with:
          app-id: ${{ vars.MINION_APPID }}
          private-key: ${{ secrets.MINION_PKEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.minion-token.outputs.token }}

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::.
          working-directory: "./antidotum/tergo"

      - name: Bump version
        working-directory: ./antidotum/tergo
        run: |
          Rscript -e "desc::desc_bump_version('dev')"
          git config --global user.email "github-ci@pagacz.io"
          git config --global user.name "Github Minion"
          version=$(Rscript -e 'desc::desc_get_version()' | cut -d' ' -f2)
          git add --all && git commit -m "Version bumped to $version [skip ci]"
          git push origin main
